blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ ä¸€èˆ¬è®¨è®º / æƒ³æ³•æ”¶é›†
    url: https://github.com/ZcY-LvTina/SegmentX/discussions
    about: ä¸å±äº Bug / åŠŸèƒ½éœ€æ±‚ / é‡æ„çš„å†…å®¹ï¼Œå¯ä»¥å‘åˆ° Discussionsã€‚
